import type { Dictionary } from "./ko";

export const en = {
  meta: { siteName: "MOOHAN Patent Translation", home: { title: "Home", description: "Professional patent translation powered by AI technology." } },
  common: { languageSwitcher: { label: "Select language" }, navigation: { home: "HOME", about: "ABOUT US", services: "SERVICES", technologies: "TECHNOLOGIES", contact: "CONTACT US" }, homeLabel: "Moohan home", primaryNavigation: "Primary navigation", footerNavigation: "Footer navigation", login: "TMS Login", backToTop: "Back to top" },
  home: {
    hero: { titleLine1: "Patent translation expertise since 2006.", titleLine2: "Powered by cutting-edge AI", description: "Since 2006, we have built deep expertise in patent translation — now enhanced by a cloud-based translation management system (TMS) and the latest AI technology. Our patent professionals, supported by AI-driven translation and verification tools, deliver precise, consistent translations that accurately support every stage of the patent lifecycle — from filing and examination to dispute resolution.", scrollDown: "SCROLL DOWN" },
    about: { label: "About Moohan", description: "Since our founding in 2006, we have provided high-quality patent translation across diverse technology fields — including patent application specifications, office action documents, and IP and litigation-related materials. Not content to rely solely on our translators' accumulated expertise, we have integrated a cloud-based translation management system (TMS) and intelligent translation support technology into our workflow to ensure more precise and consistent quality." },
    services: { label: "Services", title: "SERVICES", intro: "Patent translation is a highly specialized field that demands both legal and technical accuracy, along with strict compliance with the regulations of patent offices around the world. We combine the precise work of translators specialized by technology field with intelligent translation support technology to deliver tailored translation services optimized for every stage of patent practice — from filing and examination to dispute resolution.", items: [ { number: "01", title: "PCT National Phase Translation", description: "We provide PCT national phase entry translations that comply with the filing formats and regulations of patent offices worldwide." }, { number: "02", title: "Direct Filing Translation", description: "We provide translations formatted appropriately for direct, individual filing with patent offices in each country within the priority claim period." }, { number: "03", title: "Office Action Document Translation", description: "We provide translations of office action documents — including notices of reasons for refusal and decisions of rejection — as well as the corresponding responses and amendments." }, { number: "04", title: "IP & Litigation Translation", description: "We provide translations of specialized documents requiring a high level of legal and technical understanding, including IP-related statutes, trial and appeal decisions, court rulings, and patent infringement and dispute materials." } ], slideLabel: "Service slides", goToSlide: "Go to service" },
    technologies: { title: "TECHNOLOGIES", items: [ { title: "Rule-Based QA", description: "Completed translation files are precisely reviewed using regular expression-based rules and standardized automated review algorithms to detect errors in numbers, special characters, reference numerals, terminology, style, and more. Translators use this system as a final check before submission, while reviewers use the same system for systematic re-verification during the review stage — providing a dual quality safeguard throughout the entire translation process." }, { title: "NMT-Based Machine Translation", description: "An NMT engine specialized for the patent domain provides machine translation, allowing our expert translators to work quickly and accurately based on this foundation." }, { title: "LLM-Based AI Translation", description: "The LLM references each client's translation assets (TM/TB) and patent translation style guide to provide customized machine translation, allowing our expert translators to work quickly and accurately based on this foundation." }, { title: "LLM-Based AI Post-Editing", description: "The LLM references each client's translation assets (TM/TB) and patent translation style guide to precisely cross-verify translations for omissions, mistranslations, and contextual inconsistencies, providing revised translations and detailed comments — enabling reviewers to complete their review quickly and accurately." }, { title: "Cloud-Based Translation Platform", description: "From project setup through translation and review, we provide a unified cloud environment integrating TM, TB, and NMT/LLM. Stage-based permission management enables translators and reviewers to collaborate systematically." } ], workflowLabel: "Translation technology workflow", projectSetup: "Project Setup", connected: "Files·TM·TB·AI Engine Connected", platform: "Cloud-Based Translation Platform", environment: "Unified TM·TB·NMT/LLM Environment", translator: "Translator", reviewer: "Reviewer", nmtTranslation: "NMT/LLM Translation", initialDraft: "Initial draft generation", ruleQa: "Rule-Based QA", finalCheck: "Final check before submission", reviewCheck: "Re-verification during review", llmPostEditing: "LLM Post-Editing", revision: "Cross-verification & revision provided", complete: "Reviewed Translation Complete" },
    contact: { title: "CONTACT US", description: "Thank you for contacting us. Our team will review your inquiry and respond within 1 business day.", firstName: "First Name", lastName: "Last Name", company: "Company", email: "Email", phone: "Phone", message: "Message", attachment: "Attachment", dropGuide: "Drag files here or select the Choose File button.", uploadGuide: "Available files: JPG, GIF, PDF (maximum 10MB per file)", noFile: "No file selected.", selectedFiles: "{count} files selected.", chooseFile: "Choose File", removeFile: "Remove", submit: "Submit", sending: "Sending…", success: "Thank you. Your inquiry has been sent successfully.", error: "Unable to send your inquiry. Please try again.", invalidFile: "Only JPG, GIF, and PDF files up to 10MB each can be attached." },
    footer: { tel: "Tel", fax: "Fax", contact: "Contact", address: "Address", addressValue: "518 hausD FIRSTAR, 169-16 Gasan Digital 2-ro, Geumcheon-gu, Seoul, Korea", copyright: "©2026 MOOHAN Technical Translation Services Co., Ltd." },
  },
} satisfies Dictionary;
