import type { Dictionary } from "./ko";

export const ja = {
  meta: { siteName: "MOOHAN特許翻訳", home: { title: "Home", description: "AI技術を活用した特許専門翻訳サービス" } },
  common: { languageSwitcher: { label: "言語を選択" }, navigation: { home: "ホーム", about: "会社紹介", services: "サービス", technologies: "技術", contact: "お問い合わせ" }, homeLabel: "MOOHANホーム", primaryNavigation: "メインメニュー", footerNavigation: "フッターメニュー", login: "TMS Login", backToTop: "ページ上部へ" },
  home: {
    hero: { titleLine1: "2006年以来培ってきた特許翻訳の専門知識と、", titleLine2: "最先端AI技術の融合", description: "2006年以来培ってきた特許翻訳のノウハウに、クラウド型翻訳管理システム（TMS）と最新のAI技術を融合させました。AIを活用した翻訳・検証技術のサポートにより、特許実務の専門家は、正確かつ一貫性のある翻訳を仕上げ、出願から審査、紛争対応に至るまで、特許ライフサイクル全体にわたって的確なサポートを提供いたします。", scrollDown: "SCROLL DOWN" },
    about: { label: "MOOHANについて", description: "2006年の設立以来、無限技術翻訳は、様々な技術分野において、特許出願明細書、中間処理書類、知的財産及び訴訟関連資料に対して、高品質な特許翻訳サービスを提供してまいりました。弊社では、翻訳者の豊富な専門知識に満足することなく、クラウド型翻訳管理システム（TMS）とインテリジェント翻訳支援技術を自社プロセスに統合し、運用することで、より完璧で一貫性のある品質を実現しています。" },
    services: { label: "サービス", title: "SERVICES", intro: "特許翻訳は、法的・技術的な正確さに加え、各国の特許庁の厳格な規則への準拠が求められる高度に専門的な分野です。弊社は、特定の技術分野に精通した専門翻訳者の高度な翻訳技術とインテリジェント翻訳支援技術を組み合わせることで、出願から審査、紛争対応に至るまで、特許実務全体に最適化されたカスタマイズ翻訳サービスを提供いたします。", items: [ { number: "01", title: "PCT National Phase\nTranslation", description: "世界各国の特許庁の出願形式および規則に準拠したPCT国内移行用翻訳を提供します。" }, { number: "02", title: "Direct Filing Translation", description: "優先権主張期間内に各国特許庁へ直接出願できるよう、各国の形式に適した翻訳を提供します。" }, { number: "03", title: "Office Action Document Translation", description: "拒絶理由通知や拒絶査定などの中間処理書類、および対応する意見書・補正書の翻訳を提供します。" }, { number: "04", title: "IP & Litigation Translation", description: "知的財産関連法令、審判決定、裁判所判決、特許侵害・紛争資料など、高度な法律・技術理解を要する専門文書を翻訳します。" } ], slideLabel: "サービススライド", goToSlide: "サービスへ移動" },
    technologies: { title: "TECHNOLOGIES", items: [ { title: "Rule-Based QA", description: "正規表現ベースのルールと標準化された自動検証アルゴリズムにより、数字、特殊文字、参照番号、用語、文体などのエラーを精密に検出します。翻訳者の提出前確認とレビュー担当者の再検証に同じシステムを用い、翻訳工程全体に二重の品質保証を提供します。" }, { title: "NMT-Based Machine Translation", description: "特許分野に特化したNMTエンジンが機械翻訳を提供し、専門翻訳者が迅速かつ正確に作業できる基盤を整えます。" }, { title: "LLM-Based AI Translation", description: "LLMが顧客別翻訳資産（TM/TB）と特許翻訳スタイルガイドを参照してカスタマイズされた機械翻訳を提供します。" }, { title: "LLM-Based AI Post-Editing", description: "LLMが翻訳資産とスタイルガイドを参照し、欠落、誤訳、文脈上の不整合を精密に照合して、修正版と詳細コメントを提供します。" }, { title: "Cloud-Based Translation Platform", description: "プロジェクト設定から翻訳・レビューまで、TM、TB、NMT/LLMを統合したクラウド環境を提供します。段階別権限管理により体系的な共同作業が可能です。" } ], preparation: "Coming Soon", workflowLabel: "翻訳技術ワークフロー", projectSetup: "プロジェクト設定", connected: "ファイル・TM・TB・AIエンジン接続", platform: "クラウド型翻訳プラットフォーム", environment: "統合TM・TB・NMT/LLM環境", translator: "翻訳者", reviewer: "レビュー担当者", nmtTranslation: "NMT/LLM翻訳", initialDraft: "初稿生成", ruleQa: "ルールベースQA", finalCheck: "提出前の最終確認", reviewCheck: "レビュー時の再検証", llmPostEditing: "LLMポストエディット", revision: "照合・修正版の提供", complete: "レビュー済み翻訳完成" },
    contact: { title: "CONTACT US", description: "弊社にお問い合わせいただき、誠にありがとうございます。\n担当者がお問い合わせ内容を確認の上、1営業日以内にご返信いたします。", firstName: "氏名", lastName: "姓", company: "会社名", email: "メールアドレス", phone: "電話番号", message: "お問い合わせ内容", attachment: "添付ファイル", dropGuide: "ファイルをここにドラッグ&ドロップするか、クリックして選択してください。", uploadGuide: "アップロード可能なファイル形式:JPG、GIF、DOCX、PPTX、XLSX、PDF(1ファイルあたり最大10MB)", noFile: "ファイルが選択されていません。", selectedFiles: "{count}個のファイルを選択しました。", removeFile: "削除", privacyPolicy: "プライバシーポリシー", termsOfService: "利用規約", viewDetails: "詳細を見る", close: "閉じる", agreementRequired: "プライバシーポリシーと利用規約に同意してください。", submit: "お問い合わせ", sending: "送信中…", success: "お問い合わせを送信しました。ありがとうございます。", error: "送信できませんでした。もう一度お試しください。", invalidFile: "JPG、GIF、DOCX、PPTX、XLSX、PDF形式で、1ファイル10MB以下のもののみ添付できます。" },
    footer: { tel: "電話", telValue: "+82-2-564-7789", fax: "FAX", faxValue: "+82-2-6442-0787", contact: "メール", address: "住所", addressValue: "ソウル特別市衿川区加山デジタル2路169-16、518号（加山洞、ハウスディーファースター）", copyright: "©2026 MOOHAN特許翻訳株式会社" },
  },
} satisfies Dictionary;
