import type { Dictionary } from "./ko";

export const ja = {
  meta: { siteName: "MOOHAN特許翻訳", home: { title: "ホーム", description: "AI技術を活用した特許専門翻訳サービス" } },
  common: { languageSwitcher: { label: "言語を選択" }, navigation: { home: "ホーム", about: "会社紹介", services: "サービス", technologies: "技術", contact: "お問い合わせ" }, homeLabel: "MOOHANホーム", primaryNavigation: "メインメニュー", footerNavigation: "フッターメニュー", login: "TMSログイン", backToTop: "ページ上部へ" },
  home: {
    hero: { titleLine1: "2006年から培った特許翻訳の専門性。", titleLine2: "最先端AIで、さらなる高みへ", description: "2006年以来、特許翻訳の専門性を深め、現在ではクラウド型翻訳管理システム（TMS）と最新のAI技術を導入しています。AI翻訳・検証ツールと特許専門家の連携により、出願・審査から紛争解決まで、特許ライフサイクルのあらゆる段階を支える正確で一貫した翻訳を提供します。", scrollDown: "SCROLL DOWN" },
    about: { label: "MOOHANについて", description: "2006年の創業以来、特許出願明細書、中間処理書類、知的財産・訴訟関連文書など、多様な技術分野で高品質な特許翻訳を提供してきました。翻訳者の蓄積された専門性だけに頼らず、クラウド型翻訳管理システム（TMS）と知的翻訳支援技術を業務に統合し、より正確で一貫した品質を実現しています。" },
    services: { label: "サービス", title: "サービス", intro: "特許翻訳は、法律・技術の正確性に加え、世界各国の特許庁規則への厳格な適合が求められる高度な専門分野です。技術分野別の専門翻訳者による精緻な作業と知的翻訳支援技術を組み合わせ、出願・審査から紛争解決まで、特許実務の各段階に最適化された翻訳サービスを提供します。", items: [ { number: "01", title: "PCT国内移行翻訳", description: "世界各国の特許庁の出願形式および規則に準拠したPCT国内移行用翻訳を提供します。" }, { number: "02", title: "海外直接出願翻訳", description: "優先権主張期間内に各国特許庁へ直接出願できるよう、各国の形式に適した翻訳を提供します。" }, { number: "03", title: "中間処理書類翻訳", description: "拒絶理由通知や拒絶査定などの中間処理書類、および対応する意見書・補正書の翻訳を提供します。" }, { number: "04", title: "知的財産・訴訟翻訳", description: "知的財産関連法令、審判決定、裁判所判決、特許侵害・紛争資料など、高度な法律・技術理解を要する専門文書を翻訳します。" } ], slideLabel: "サービススライド", goToSlide: "サービスへ移動" },
    technologies: { title: "技術", items: [ { title: "ルールベースQA", description: "正規表現ベースのルールと標準化された自動検証アルゴリズムにより、数字、特殊文字、参照番号、用語、文体などのエラーを精密に検出します。翻訳者の提出前確認とレビュー担当者の再検証に同じシステムを用い、翻訳工程全体に二重の品質保証を提供します。" }, { title: "NMT機械翻訳", description: "特許分野に特化したNMTエンジンが機械翻訳を提供し、専門翻訳者が迅速かつ正確に作業できる基盤を整えます。" }, { title: "LLM AI翻訳", description: "LLMが顧客別翻訳資産（TM/TB）と特許翻訳スタイルガイドを参照してカスタマイズされた機械翻訳を提供します。" }, { title: "LLM AIポストエディット", description: "LLMが翻訳資産とスタイルガイドを参照し、欠落、誤訳、文脈上の不整合を精密に照合して、修正版と詳細コメントを提供します。" }, { title: "クラウド型翻訳プラットフォーム", description: "プロジェクト設定から翻訳・レビューまで、TM、TB、NMT/LLMを統合したクラウド環境を提供します。段階別権限管理により体系的な共同作業が可能です。" } ], workflowLabel: "翻訳技術ワークフロー", projectSetup: "プロジェクト設定", connected: "ファイル・TM・TB・AIエンジン接続", platform: "クラウド型翻訳プラットフォーム", environment: "統合TM・TB・NMT/LLM環境", translator: "翻訳者", reviewer: "レビュー担当者", nmtTranslation: "NMT/LLM翻訳", initialDraft: "初稿生成", ruleQa: "ルールベースQA", finalCheck: "提出前の最終確認", reviewCheck: "レビュー時の再検証", llmPostEditing: "LLMポストエディット", revision: "照合・修正版の提供", complete: "レビュー済み翻訳完成" },
    contact: { title: "お問い合わせ", description: "お問い合わせありがとうございます。担当チームが内容を確認し、1営業日以内にご返信いたします。", firstName: "名", lastName: "姓", company: "会社名", email: "メール", phone: "電話番号", message: "お問い合わせ内容", attachment: "添付ファイル", dropGuide: "ファイルをここにドラッグするか、ファイル選択ボタンを押してください。", uploadGuide: "対応形式：JPG、GIF、PDF（1ファイル最大10MB）", noFile: "ファイルが選択されていません。", selectedFiles: "{count}個のファイルを選択しました。", chooseFile: "ファイル選択", removeFile: "削除", submit: "送信", sending: "送信中…", success: "お問い合わせを送信しました。ありがとうございます。", error: "送信できませんでした。もう一度お試しください。", invalidFile: "JPG、GIF、PDF形式で、1ファイル10MB以下のもののみ添付できます。" },
    footer: { tel: "電話", fax: "FAX", contact: "メール", address: "住所", addressValue: "韓国 ソウル特別市衿川区加山デジタル2路169-16 hausD FIRSTAR 518号", copyright: "©2026 MOOHAN特許翻訳株式会社" },
  },
} satisfies Dictionary;
