import type { Dictionary } from "./ko";

export const zh = {
  meta: { siteName: "无限技术翻译", home: { title: "HOME", description: "自2006年积累至今的专利翻译专业实力与前沿AI技术的结合" } },
  common: { languageSwitcher: { label: "Language" }, navigation: { home: "HOME", about: "ABOUT US", services: "SERVICES", technologies: "TECHNOLOGIES", contact: "CONTACT US" }, homeLabel: "无限技术翻译首页", primaryNavigation: "主导航", footerNavigation: "页脚导航", login: "TMS Login", backToTop: "返回顶部" },
  home: {
    hero: { titleLine1: "自2006年以来积累的专利翻译专业实力与前沿AI技术的结合", titleLine2: "", description: "我们将自2006年以来积累的专利翻译经验，与基于云端的翻译管理系统（TMS）及最新AI技术相结合。我们的专利翻译团队在基于AI的翻译与审校技术支持下，完成精准且一致的翻译，并为从申请、审查到纠纷应对的整个专利生命周期提供有力支持。", scrollDown: "SCROLL DOWN" },
    about: { label: "ABOUT US", description: "自2006年成立以来，无限技术翻译（MOOHAN Technical Translation Services）一直为各技术领域的专利说明书、中间文件、IP及诉讼相关资料提供高品质的专利翻译服务。无限技术翻译并不止步于资深译员的专业能力，而是将基于云端的翻译管理系统（TMS）与智能翻译辅助技术整合到自身流程中并加以运用，以确保更加精准、一致的翻译品质。" },
    services: { label: "SERVICES", title: "SERVICES", intro: "专利翻译是一个必须同时满足法律与技术准确性，并符合各国专利局严格规定的高度专业领域。无限技术翻译将各技术领域资深译员的专业能力与智能翻译辅助技术相结合，针对从申请、审查到纠纷应对等专利实务全流程，提供定制化翻译服务。", items: [ { number: "01", title: "PCT进入国家阶段翻译", description: "提供符合各国专利局申请格式与规定的PCT进入国家阶段的翻译服务。" }, { number: "02", title: "巴黎公约直接申请翻译", description: "在优先权期限内向各国专利局直接提交申请时，提供符合相应格式要求的翻译服务。" }, { number: "03", title: "中间文件翻译", description: "提供审查意见通知书、驳回决定书等中间文件及相应的意见陈述书、补正书的翻译服务。" }, { number: "04", title: "IP及诉讼相关资料翻译", description: "提供针对IP相关法令、审决书、判决书及专利侵权·纠纷资料等需要高度法律与技术理解能力的专业文件的翻译服务。" } ], slideLabel: "服务轮播", goToSlide: "转到服务" },
    technologies: { title: "TECHNOLOGIES", items: [ { title: "基于规则的QA", description: "对已完成翻译的文件，通过基于正则表达式的规则及标准化的自动校对算法进行精准审校，排查数字、特殊符号、附图标记、术语、格式等方面的错误。译者可将其作为提交前的最终检查工具，审校者则可将其作为审校阶段的系统性复核工具，借助同一套系统，在整个翻译流程中提供双重质量保障。" }, { title: "基于NMT的机器翻译", description: "面向专利领域的NMT引擎提供机器翻译服务，专业译者可在此基础上快速、准确地完成翻译。" }, { title: "基于LLM的AI翻译", description: "LLM参照各客户专属翻译资产（TM/TB）及专利翻译风格指南，提供符合客户需求的定制化机器翻译，专业译者可在此基础上快速、准确地完成翻译。" }, { title: "基于LLM的AI后编辑", description: "LLM参照各客户专属翻译资产（TM/TB）及专利翻译风格指南，对译文中的漏译、误译、上下文不一致等问题进行精准交叉验证，并提供修改译文及详细意见，从而帮助审校者快速、准确地完成审校工作。" }, { title: "基于云端的翻译平台", description: "从项目设置到翻译、审校的全过程中，提供将TM、TB、NMT/LLM整合为一体的云端环境，并通过分级权限管理，使译者与审校者能够高效协作。" } ], preparation: "Coming Soon", workflowLabel: "翻译技术工作流程", projectSetup: "PM：项目设置", connected: "文件·TM·TB·AI引擎的联动", platform: "基于云端的翻译平台", environment: "TM·TB·NMT/LLM 整合环境", translator: "译者", reviewer: "审校者", nmtTranslation: "NMT/LLM翻译", initialDraft: "初稿生成", ruleQa: "基于规则的QA", finalCheck: "提交前最终检查", reviewCheck: "审校阶段再确认", llmPostEditing: "LLM 后编辑", revision: "交叉验证并提供修改方案", complete: "审校完成的译文" },
    contact: { title: "CONTACT US", description: "负责人确认您的咨询内容后，将在1个工作日内回复。", firstName: "姓名", lastName: "姓", company: "公司名称", email: "邮箱", phone: "联系方式", message: "咨询内容", attachment: "附件", dropGuide: "请将文件拖拽到此处，或点击选择文件。", uploadGuide: "支持的文件格式：JPG、GIF、DOCX、PPTX、XLSX、PDF（每个文件最大10MB）", noFile: "未选择文件。", selectedFiles: "已选择{count}个文件。", removeFile: "删除", privacyPolicy: "隐私政策", termsOfService: "服务条款", viewDetails: "查看详情", close: "关闭", agreementRequired: "请同意隐私政策和服务条款。", submit: "提交咨询", sending: "提交中…", success: "感谢您，咨询已成功受理。", error: "无法提交咨询，请重试。", invalidFile: "仅可附加JPG、GIF、DOCX、PPTX、XLSX、PDF文件，每个文件最大10MB。" },
    footer: { tel: "电话", telValue: "+82-2-564-7789", fax: "传真", faxValue: "+82-2-6442-0787", contact: "邮箱", address: "地址", addressValue: "韩国首尔特别市衿川区加山数码2路169-16 hausD FIRSTAR 518室", copyright: "©2026 MOOHAN专利翻译有限公司" },
  },
} satisfies Dictionary;
